name: Build docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

   # Build Docker Image
      # -----------------------------
      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build Image
        run: |
          docker build -t netflix_backend-main:latest .

      # =============================
      # PUSH TO AWS (ECR)
      # =============================
      # #- name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Login to ECR
      #   run: |
      #     ECR_URI=$(aws ecr describe-repositories \
      #       --repository-names ${{ secrets.ECR_REPOSITORY }} \
      #       --query "repositories[0].repositoryUri" \
      #       --output text)

      #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
      #     | docker login --username AWS --password-stdin $(echo $ECR_URI | cut -d'/' -f1)

      # - name: Tag for ECR
      #   run: |
      #     docker tag movie-backend:latest $ECR_URI:latest

      # - name: Push to ECR
      #   run: |
      #     docker push $ECR_URI:latest