name: Build docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: ${{ secrets.AWS_REGION }}

    #Login to ECR  
    #==============
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
   # Build Docker Image
      # -----------------------------
      - name: Build JAR
        run: |
          mvn clean package 

      - name: Build Image
        run: |
          echo "${{ vars.ENV_FILE }}" > .env 
          ls -la
          docker build -t netflix_backend-main:latest .

      - name: Docker push
        run: |
          docker tag netflix_backend-main:latest ${{ secrets_AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/netflix_backend-main:${GITHUB_RUN_NUMBER}
          docker push  ${{ secrets_AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/netflix_backend-main:${GITHUB_RUN_NUMBER}
